export PASSWORD_STORE_CLIP_TIME=30
export PASSWORD_STORE_GENERATED_LENGTH=25
export PASSWORD_STORE_CHARACTER_SET="A-Za-z0-9<>?,./:;{}|[]~\!@#$%^&*()_+=\-"
export PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS="[:alnum:]"
export PASSWORD_STORE_ENABLE_EXTENSIONS="true"

